# Generated by Django 3.2.12 on 2022-10-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticalRoom',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('botany', models.CharField(max_length=100)),
                ('chemistry', models.CharField(max_length=100)),
                ('physics', models.CharField(blank=True, max_length=100)),
                ('c_programming', models.CharField(max_length=50)),
                ('data_structure', models.CharField(max_length=100)),
                ('electronics', models.CharField(max_length=50)),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
