# Generated by Django 3.2.12 on 2022-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0003_practicalroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalroom',
            name='electronics',
            field=models.CharField(max_length=100),
        ),
    ]
