# Generated by Django 3.2.12 on 2022-10-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('College', '0004_alter_practicalroom_electronics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(max_length=255, upload_to='')),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
