# Generated by Django 3.2.12 on 2022-10-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_alter_practicalroom_electronics'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClgSubject',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('subject_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('course_no', models.IntegerField()),
                ('staff_no', models.IntegerField()),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
