# Generated by Django 3.2.12 on 2022-10-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_alter_practicalroom_electronics'),
        ('Student', '0003_onlinestudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libreary',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('books', models.CharField(max_length=255)),
                ('all_type_book', models.IntegerField()),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
