# Generated by Django 3.2.12 on 2022-10-25 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_alter_practicalroom_electronics'),
        ('Student', '0004_libreary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('subject', models.IntegerField()),
                ('langauge', models.IntegerField()),
                ('spoken_english', models.IntegerField()),
                ('MSCIT', models.IntegerField()),
                ('typing', models.IntegerField()),
                ('NEET', models.IntegerField()),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
