# Generated by Django 3.2.12 on 2022-10-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('College', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInform',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('educations', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.IntegerField()),
                ('dep', models.CharField(max_length=100)),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
