# Generated by Django 3.2.12 on 2022-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrandTeacher', '0002_collegestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='division',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
