# Generated by Django 3.2.12 on 2022-10-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0002_department'),
        ('GrandTeacher', '0003_alter_collegestudent_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubject',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('science', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100)),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
