# Generated by Django 3.2.12 on 2022-10-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0004_alter_practicalroom_electronics'),
        ('GrandTeacher', '0005_addmissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='College.mybasemodel')),
                ('Bcs', models.IntegerField()),
                ('Bcom', models.IntegerField()),
                ('Ba', models.IntegerField()),
                ('Bsc', models.IntegerField()),
            ],
            bases=('College.mybasemodel',),
        ),
    ]
